import SideBar from '../components/SideBar'
import '../styles/globals.css'
import {getServerSession} from 'next-auth'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import { SessionProvider } from '../components/SessionProvider'
import Login from '../components/Login'
import ClinetProvider from '../components/ClinetProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {
            !session?(
            <Login/>
            ):(
              <div className='flex'>
          {/*SideBar*/}
          <div className='bg-[#202123] max-w-xs h-screen 
          overflow-y-auto md:min-w-[20rem]
          '>
            <SideBar/>
          </div>
          {/*CLinetProvider - Notifications*/}
            <ClinetProvider/>
         <div className='bg-[#343541] flex-1'>{children}</div>
          </div>
            )
          }
         
          </SessionProvider>
        </body>
    </html>
  )
}
